from __future__ import annotations

import argparse
import json
import wave
from pathlib import Path

import numpy as np



def _envelope(length: int, rng: np.random.Generator) -> np.ndarray:
    attack = max(1, int(length * rng.uniform(0.005, 0.08)))
    decay = np.exp(-np.linspace(0, rng.uniform(2.0, 8.0), length))
    decay[:attack] *= np.linspace(0, 1, attack)
    return decay


def render_species(species: str, duration: float, sample_rate: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    count = int(duration * sample_rate)
    output = np.zeros(count, dtype=np.float64)
    cursor = 0
    while cursor < count:
        event_length = min(count - cursor, int(sample_rate * rng.uniform(0.08, 1.8)))
        t = np.arange(event_length) / sample_rate
        env = _envelope(event_length, rng)
        if species == "pulse":
            frequency = 55.0 * 2 ** rng.uniform(0, 4)
            carrier = np.sin(2 * np.pi * frequency * t + rng.uniform(0, 2 * np.pi))
            carrier += 0.35 * np.sin(2 * np.pi * frequency * rng.choice([1.5, 2, 3]) * t)
            event = np.tanh(carrier * rng.uniform(1.0, 3.5)) * env
        elif species == "resonance":
            base = 45.0 * 2 ** rng.uniform(0, 4.5)
            event = sum(
                np.sin(2 * np.pi * base * (partial + rng.uniform(-0.025, 0.025)) * t + rng.uniform(0, 6.28)) / partial
                for partial in range(1, rng.integers(3, 9))
            ) * env
        elif species == "texture":
            noise = rng.normal(0, 1, event_length)
            kernel_size = min(event_length, int(rng.uniform(8, 180)))
            kernel = np.hanning(kernel_size)
            kernel /= max(kernel.sum(), 1e-9)
            event = np.convolve(noise, kernel, mode="same") * env * np.sqrt(kernel_size)
        else:
            raise ValueError(f"unknown species: {species}")
        output[cursor : cursor + event_length] += event * rng.uniform(0.15, 0.65)
        cursor += max(1, int(event_length * rng.uniform(0.25, 0.95)))
    peak = max(np.max(np.abs(output)), 1e-9)
    return np.tanh(output / peak * 1.25) * 0.75


def write_species(path: Path, species: str, duration: float, sample_rate: int, seed: int, chunk_seconds: float = 20.0) -> None:
    """Stream long corpora to disk so the 30-minute default stays memory bounded."""
    path.parent.mkdir(parents=True, exist_ok=True)
    remaining = duration
    chunk = 0
    with wave.open(str(path), "wb") as output:
        output.setnchannels(1)
        output.setsampwidth(2)
        output.setframerate(sample_rate)
        while remaining > 1e-9:
            current = min(remaining, chunk_seconds)
            audio = render_species(species, current, sample_rate, seed + chunk * 1009)
            pcm = (np.clip(audio, -1, 1) * 32767).astype("<i2")
            output.writeframes(pcm.tobytes())
            remaining -= current
            chunk += 1


def generate(output: Path, duration: float, sample_rate: int, seed: int) -> dict:
    files = []
    for index, species in enumerate(("pulse", "resonance", "texture")):
        path = output / f"{species}.wav"
        write_species(path, species, duration, sample_rate, seed + index)
        files.append({"species": species, "path": path.name, "seconds": duration})
    manifest = {
        "license": "CC0-1.0 / procedurally generated by this repository",
        "sample_rate": sample_rate,
        "seed": seed,
        "files": files,
    }
    output.mkdir(parents=True, exist_ok=True)
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate owned abstract-electronic RAVE/BRAVE test material.")
    parser.add_argument("output", type=Path)
    parser.add_argument("--duration", type=float, default=1800, help="seconds per species")
    parser.add_argument("--sample-rate", type=int, default=48_000)
    parser.add_argument("--seed", type=int, default=20260714)
    args = parser.parse_args()
    print(json.dumps(generate(args.output, args.duration, args.sample_rate, args.seed), indent=2))


if __name__ == "__main__":
    main()
